location           = "canadacentral"
environment        = "dev"
resource_group_name = "my-rg-dev"
subscription_id = "a3fcb44b-8229-4e41-99c5-fbebb9ffb8bf"
container_name       = "tfstate-nb01"
key                  = "dev.terraform.tfstate"